[package]
name = "dapviz"
version = "0.1.0"
edition = "2021"

[dependencies]

dap-types = { path = "../dap-types" }

anyhow = "1.0.93"
axum = { version = "0.7.5", features = ["tracing", "macros", "http2", "ws"] }
bytes = "1.7.2"
clap = { version = "4.5.16", features = ["derive"] }
serde = { workspace = true}
serde_json = { workspace = true}
tokio = { version = "1.39.3", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["fmt", "env-filter"] }
backoff = { version = "0.4.0", features = ["tokio"] }
enum_dispatch = "0.3.13"

