[package]
name = "dapviz"
version = "0.1.0"
edition = "2021"

[dependencies]

dap-types = { path = "../dap-types" }

anyhow = "1.0.94"
axum = { version = "0.7.9", features = ["tracing", "macros", "http2", "ws"] }
bytes = "1.9.0"
clap = { version = "4.5.23", features = ["derive"] }
serde = { workspace = true}
serde_json = { workspace = true}
tokio = { version = "1.42.0", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["fmt", "env-filter"] }
backoff = { version = "0.4.0", features = ["tokio"] }
enum_dispatch = "0.3.13"

