[workspace]

resolver = "2"

members = [
    "server",
    "dap-types"
]

[workspace.dependencies]
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"

[profile.release]
lto = "fat"
codegen-units = 1
strip = "symbols"

